version: '3'
services:
  mysql-standalone:
    image: mysql:8.0
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=smartcontact
      - MYSQL_USER=rahul
      - MYSQL_PASSWORD=abc123
    ports:
      - 3306:3306

  smartcontact:
    image: vaibhav15/smartcontact:1.0.0
    depends_on:
      - mysql-standalone
    restart: always
    ports:
      - 8081:8081